Fix CompositePK_Test.CP5_Composite_ObjectIdentity().
The tests was bad, as it was explicitly referencing ProductID=2 and OrderID=1,
which may not exist (and in fact, does not exist in SQL Server Northwind).

However, fixing the test to be sane shows that L2SQL has a bug, as this:

	db.OrderDetails.First();

causes:

	System.InvalidCastException: Specified cast is not valid
	at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)
	at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)
	at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
	at System.Data.Linq.Table`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
	at System.Linq.Queryable.First[TSource](IQueryable`1 source)
	at Test_NUnit_MsSql_Strict.CompositePK_Test.CP5_Composite_ObjectIdentity()

So, unmark this as an [Explicit] DbLinq.SqlServer_test bug (as fixing the test
fixed it for DbLinq.SqlServer_test), but do make it [Explicit] for L2SQL.